### ISSUE TITLE
Problem with latest gridExtra

### ISSUE THREAD

**Issue by welchr** [welchr/LocusZoom#16]
---------- Forwarded message ----------
Date: Sunday, July 26, 2015
Subject: Error when creating plot with LocusZoom stand-alone

I am getting this error when creating a plot with LocusZoom stand-alone:

```
Error in gtable_table(d, name = "core", fg_fun = theme$core$fg_fun, bg_fun = theme$core$bg_fun,  : 

  unused argument (show.rownames = FALSE)

Calls: grid.extralog -> grid.draw -> tableGrob -> gtable_table

recover called non-interactively; frames dumped, use debugger() to view
```

It doesn't occur if I remove the gridExtra R package. I have the latest version of R, BioC and LocusZoom.

**Comment by rpruim** [comment]
Hello from GR (just recently back from a semester in New Zealand).  Hope things are going well for you.  

The gridExtra package did just go through a major update and package maintainers who relay on it were warned that this was coming, but I haven’t had time to look into it much.  It may be possible to just drop the use of show.rownames to make the problem go away.

Does our code check for gridExtra and avoid it if it isn’t there?  I’m trying to figure out why things work if gridExtra is removed.

I’ll see if I can find some time to look at this today or tomorrow, but I am leaving town again on Wednesday and won’t be back until next Tuesday.

—rjp

PS.  One of my former students (Peter Vandehaar is coming to Ann Arbor to work with Mike and Goncalo starting in a few weeks and I think he plans to start working on a bioinformatics degree in January.

**Comment by rpruim** [comment]
It looks like some recent changes in `gridExtra` have broken a couple things:

  * `stextGrob()` is defunct.  There was already a back-up plan for when `gridExtra` was not available.  That can become the standard (i.e. only) option.
  * the `show.rownames` argument has been removed from `tableGrob()`.  The error message above can be avoided by not using that argument anymore.

While we are at this, I've modified things so that `gridExtra` is not added to the search path by our code.

Pending some testing, it looks like we should have this repaired soon.

**Comment by welchr** [comment]
Thanks, Randy. I put in a helper function to deal with the two versions of gridExtra: 

```
# Helper function to draw table grobs on the log page. Prints the table without rownames.
# This handles the two different gridExtra package versions with different interfaces.
draw_table = function(...) {
  ge_version = as.character(packageVersion("gridExtra"))
  vcomp = compareVersion(ge_version,"2.0.0")
  if (vcomp == -1) {
    grid.draw(tableGrob(
      ...,
      show.rownames = F
    ))
  } else {
    grid.draw(tableGrob(
      ...,
      rows = NULL
    ))
  }
}
```

If you want to do something like this in your branch (or different approach) that would be great, otherwise I can wait for your commit and patch on top of it.

**Comment by rpruim** [comment]
I already pushed the gridExtra2 branch, and it only modifies very few lines (3 or 4 I think), so you should be able to easily merge what I’ve done — even just by hand.

Do you want to deal with two version of gridExtra or just require people to get the newest one?

**Comment by welchr** [comment]
Sounds great. 

For now it seems OK to support them both, since it's a small patch, and our cluster environment still uses 0.9.1. We could remove and only support 2.x in the future?
