### ISSUE TITLE
Relax specifying --refsnp

### ISSUE THREAD

**Issue by welchr** [welchr/LocusZoom#19]
- [x] Allow 15:949494 instead of chr15:949494 (chr really isn't important)
- [x] Allow 15:949494_G/C, ignore alleles, and generate suitable warning that the alleles are not considered

**Comment by swvanderlaan** [comment]
Actually, aren't the alleles important? Because theoretically variants could be located on the same location?

**Comment by welchr** [comment]
Very important, but unfortunately this old locuszoom doesn't consider alleles anywhere currently. I would imagine fixing the code to handle this would be a fair amount of work, and would also require users to start providing only files that specify either chrom/pos/ref/alt, or rsID (right now, they only have to specify chrom/pos if no rsID). 

The new locuszoom.js handles this much better, though we've unfortunately not yet implemented "plot with your own data."
