### ISSUE TITLE
Please update outdated GWAS_CAT_URL

### ISSUE THREAD

**Issue by marcora** [welchr/LocusZoom#21]
Please update GWAS_CAT_URL to ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-catalog-associations.tsv

**Comment by marcora** [comment]
Please update GWAS_CAT_URL to ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-catalog-associations.tsv

**Comment by welchr** [comment]
Fixed on 3e5a552c254efa71d0a996bdea3a7586a89796d7.
